In [1]:
import numpy as np

In [33]:
#Ex1
#Given, there are 5 numbers in the data set: (8, 12, 16, 24, 4). What is the standard deviation? And, what will be the sum of deviations of individual data points from their mean?
dataset=[8,12,16,24,4]
a=np.std(dataset)
print(a)
y=0
z=np.mean(dataset)
print(z)
for x in dataset:
    y=y+z-x
print(y)

6.881860213634101
12.8
3.552713678800501e-15


In [ ]:
#Ex2
#If some outliers are introduced to the dataset, what will happen to the Standard Deviation? Will it increase, decrease or remain the same?
# This will increase the Standard Deviation.

In [ ]:
#Ex3
#Suppose the below positively skewed distribution has a median of 30, which of the following statement is true?

#A) Mean is greater than 30 - True
#B) Mean is less than 30 - False
#C) Mode is greater than 30 - False
#D) Mode is less than 30 - True
#E) Both A and D - True
#F) Both B and C - False

In [ ]:
#Ex4
#Which value can be the possible value for the median of the below distribution?
#Assume the data are distributed as follows:

#[10, 10, 10, 10, 11, 11, 12, 13, 14 ]
#[15, 15, 15, 16, 16, 16, 16, 16, 17, 18, 19, 19]
#[20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24]
#[26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 29, 29, 29, 29, 29, 29, 29, 29, 29]
#[30, 30, 30, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34]
#[35, 35, 35, 37, 37, 37, 37, 39, 39, 39]
#[40, 40, 43, 43, 44, 44]
#[46, 46, 46, 47, 49]
#[52, 53, 54]

# 31 would be the median for this data

In [ ]:
#Ex5-6-7
#What is the shape of the distribution? (no Numpy)
#positive skewed or right skewed
#What would you consider to be the most appropriate measure of the center for this data?
#Median would be the most appropriate since it is less affected by outliers
#If Y axis represents the number of individuals and X axis – salary of the individual in thousands. How many individuals have salary less than 10 thousands? (no Numpy)
#710

In [42]:
#Ex8
#We have a set of positive numbers. If a single value of the set is altered what must change?

#A) Mean
#B) Median
#C) Mode
#D) All of these

#Hint: try to create a Numpy array and calculate mean median and mode, then alter it and see what changes

a = np.array([[9,13,4,5],[7,3,21,6],[9,13,6,7]])
print(np.mean(a))
print(np.median(a))
from scipy import stats
m=stats.mode(a)
print(m)

8.583333333333334
7.0
ModeResult(mode=array([[ 9, 13,  4,  5]]), count=array([[2, 2, 1, 1]]))


In [44]:
#Ex9
#Calculate the standard deviation of the salaries of the 10 employees.
a=np.array([[25,3],[40,2],[35,1],[50,4]])
np.std(a)


18.641351882307248

In [ ]:
#Ex10
#Which of the following random variables is discrete?

#A) the length of time a battery lasts
#B) the number of pens purchased by a student in a year
#C) the percentage of cows in a cattle firm that have been vaccinated
#D) the distance between a pair of towns

# only B

In [ ]:
#Ex11
#Which of the below normal distributions will have the greatest spread?

#A) mu=5, sigma =1.5
#B) mu=10, sigma =1.0
#C) mu=5, sigma =1.65
#D) mu=8, sigma =1.2
#E) mu=10, sigma =1.6

#mu indicates mean, sigma indicates std dev.
#C would have the greatest spread


In [4]:
#Op1
import numpy as np

In [45]:
#op2
np.version.version

'1.20.1'

In [47]:
#op3
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
#op4
x = np.array([[100, 20, 34],
              [3, 466, 5]])
 
print("Size of the array: ",
      x.size)
 
print("Memory size of one array element in bytes: ",
      x.itemsize)
 
# memory size of numpy array
print("Memory size of numpy array in bytes:",
      x.size * x.itemsize)

print(x.nbytes)

Size of the array:  6
Memory size of one array element in bytes:  4
Memory size of numpy array in bytes: 24
24


In [13]:
#op5
print(np.info(np.add))


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [14]:
#op6
x=np.zeros(10)
x[5]=1
print(x)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [16]:
#op7
x=np.linspace(10,49,30)
print(x)

[10.         11.34482759 12.68965517 14.03448276 15.37931034 16.72413793
 18.06896552 19.4137931  20.75862069 22.10344828 23.44827586 24.79310345
 26.13793103 27.48275862 28.82758621 30.17241379 31.51724138 32.86206897
 34.20689655 35.55172414 36.89655172 38.24137931 39.5862069  40.93103448
 42.27586207 43.62068966 44.96551724 46.31034483 47.65517241 49.        ]


In [21]:
#op8
x=np.flip(x)
print(x)

[49.         47.65517241 46.31034483 44.96551724 43.62068966 42.27586207
 40.93103448 39.5862069  38.24137931 36.89655172 35.55172414 34.20689655
 32.86206897 31.51724138 30.17241379 28.82758621 27.48275862 26.13793103
 24.79310345 23.44827586 22.10344828 20.75862069 19.4137931  18.06896552
 16.72413793 15.37931034 14.03448276 12.68965517 11.34482759 10.        ]


In [32]:
#op9
y=np.linspace(0,8,9)
print(y)
y=y.reshape(3,3)
print(y)


[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [40]:
#op10
x=[1,2,0,0,4,0]
a=[]
for i in range(len(x)):
    if x[i]==0: 
        a.append(i)
print(a)



[2, 3, 5]


In [42]:
#op10

[i for i, e in enumerate(x) if e == 0]

[2, 3, 5]

In [45]:
#op11
x=np.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [54]:
#op12
x=np.random.rand(3,3,3)
print(x)


[[[0.94955169 0.41599831 0.69894005]
  [0.11164767 0.0211804  0.40327694]
  [0.83014655 0.48440728 0.88734618]]

 [[0.02985235 0.25450644 0.51411667]
  [0.48115748 0.26015994 0.44707887]
  [0.09331111 0.51272514 0.94795428]]

 [[0.21608406 0.43981424 0.05833283]
  [0.18741474 0.16395992 0.35856939]
  [0.72483655 0.21126464 0.89912693]]]


In [55]:
#op13
y=np.random.rand(10,10)
print(y)
y.max()


[[0.42685029 0.66355833 0.19846894 0.65953613 0.29955138 0.9391018
  0.42410414 0.955849   0.51447972 0.856439  ]
 [0.72158999 0.53389603 0.9566275  0.68448116 0.2235521  0.95662718
  0.13543434 0.45501606 0.25494341 0.9091659 ]
 [0.52161768 0.25225165 0.99027868 0.79581586 0.43727848 0.3137245
  0.93592362 0.93459987 0.95077715 0.46019137]
 [0.48692703 0.52525771 0.35560857 0.83380064 0.45021855 0.7512785
  0.07181074 0.08517619 0.65028467 0.32267785]
 [0.29297954 0.3827309  0.75420021 0.5751786  0.91385483 0.78486709
  0.2967519  0.29240875 0.95289103 0.88451604]
 [0.62654583 0.64977629 0.65751086 0.26289269 0.45704997 0.44386893
  0.37919289 0.7251481  0.54050047 0.228048  ]
 [0.36799906 0.2586833  0.35449841 0.79099322 0.41060577 0.19332939
  0.87650927 0.19631836 0.40480515 0.58291792]
 [0.99274481 0.68144392 0.63934789 0.51517169 0.85604609 0.16370386
  0.84232238 0.21369132 0.68438275 0.52836873]
 [0.1435522  0.12323586 0.63526622 0.86680563 0.99319598 0.75939098
  0.23912428 0.

0.9931959800416842

In [62]:
#op14
x = np.random.randint(0,100,30)
#print(x)

np.mean(x)


51.8

In [79]:
#op15
x=np.ones((6,7)) 
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [80]:
#op16
x=np.pad(x, pad_width=1, mode="constant", constant_values=0)
#print(np.info(np.pad))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [81]:
#op17
# wait, what is it false ?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [86]:
#op19
Z = np.zeros((8,8),dtype=int)
Z[1::3,::3] = 1
#Z[::2,1::2] = 1
print(Z)

[[0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 1 0]]


In [82]:
#op24
a=[[1,2,3],[3,4,5],[4,5,6],[5,6,7],[6,78,8]]
b=[[1,2],[2,3],[4,5]]
Z = np.dot(a, b)
print(Z)

[[ 17  23]
 [ 31  43]
 [ 38  53]
 [ 45  63]
 [194 286]]
